- name: Construct CloudFormation {{ ENV_NAME }}-stack
  cloudformation:
    aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
    aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
    region: "{{ AWS_REGION }}"
    stack_name: "{{ ENV_NAME }}-stack"
    state: present
    disable_rollback: false
    template: "{{ CLOUDFORMATION_TEMPLATE_DIR }}/{{ TEMPLATE_FILE }}"
  args:
    template_parameters:
      Version: "{{ VERSION }}"
      EnvName: "{{ ENV_NAME }}"
      AdminCIDR: "{{ ADMIN_IP }}"
