- name: Construct CloudFormation {{ ENV_NAME }}-shadowsocks
  cloudformation:
    aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
    aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
    region: "{{ AWS_REGION }}"
    stack_name: "{{ ENV_NAME }}-shadowsocks"
    state: absent